# PIAIC 
# Session II (assignment#1)

PIAIC_Hafiz Muhammad Sarmad Khan_PIAIC101225

# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

# Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))           

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)            #shape

(3,)


In [ ]:
print(a[0], a[1], a[2])   

1 2 3


In [ ]:
a[0] = 5                  # Change an element of the array
print(a)                

[5 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                  

(2, 3)


In [ ]:
print(b[0, 0], b[0, 1], b[1, 0])  

1 2 4


Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)           
                    

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((1,2))    # Create an array of all ones
print(b)           

[[1. 1.]]


In [ ]:
c = np.full((2,2), 7)  # Create a constant array
print(c)             
                  

[[7 7]
 [7 7]]


In [ ]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)       
                 

[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                   

[[0.88607874 0.77165345]
 [0.07711568 0.26148007]]


In [ ]:
e = np.random.random((3,3))  # Create an array filled with random values
print(e)                   

[[0.66900362 0.67537297 0.06863519]
 [0.69605962 0.02697315 0.28847412]
 [0.17029372 0.95188384 0.36115978]]


In [ ]:
import numpy as np
my_list = [0,1,2,3,4,5,6,7,8,9,10]
nparr = np.array(my_list)
print(nparr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Creates an array of the integers from 10 to 50

arr_10to50 = np.arange(10,51)
print(arr_10to50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#Create an array of the even integers from 10 to 50

arr_10to50_even = np.arange(10,51,2)
print(arr_10to50_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#Use NumPy to generate a random number between 0 and 1

np.random.rand(1)

array([0.76537972])

In [ ]:
#Use NumPy to generate 25 random numbers sampled from a standard normal distribution

np.random.randn(25)

array([ 0.67965392,  0.02707526,  0.37563907,  0.223782  , -0.1525565 ,
       -0.88684782,  0.3481587 ,  1.41214962, -1.88123971, -0.62504733,
       -1.07765589, -0.8136244 ,  1.95964026, -0.75202695, -0.74188789,
        1.65664209,  2.65236212, -2.11108356,  1.86329623,  0.16474081,
        0.4003029 , -0.13402519, -0.37149779,  0.07899342, -1.54049591])

In [ ]:
#Create a matrix of 100 items spaced equally at 0.01 steps ranged from 0.01 to 1

np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
#Returning the exact same result as above:

np.linspace(0.01,1, 100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
#Create an array of 20 linearly spaced points between 0 and 1

np.linspace(0,1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Array indexing

Numpy offers several ways to index into arrays.

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
# Using slice to pull out the subarray consisting of the first 2 rows and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]

In [ ]:
# A slice of an array is a view into the same data, so modifying it will modify the original array.
print(a[0, 1])  
b[0, 0] = 77    
print(a[0, 1])  

2
77


We can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
# Two ways of accessing the data in the middle row of the array.
#Mixing integer indexing with slices yields an array of lower rank, while using only slices yields an array of the same rank as theoriginal array:

row_r1 = a[1, :]   
row_r2 = a[1:2, :]  
print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)  

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [ ]:
# We can make the same distinction when accessing columns of an array:

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape) 
print(col_r2, col_r2.shape) 
          
                

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
# random 2d array

arr_2_d = np.arange(1,26).reshape(5,5)
print(arr_2_d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
arr_2_d[3,4]

20

In [ ]:
#Using Indexing & Slicing, grab items 2, 7, 12 of the arr_2_d array

arr_2_d[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
#Using Indexing & Slicing, grab the last row of the arr_2_d array

arr_2_d[4,:]

array([21, 22, 23, 24, 25])

In [ ]:
#Get the sum of all the values in arr_2_d array

np.sum(arr_2_d)

325

In [ ]:
#Get the standard deviation of the values in arr_2_d array

np.std(arr_2_d)

7.211102550927978

In [ ]:
#Get the sum of the Columns values in arr_2_d array

arr_2_d.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
#Get the sum of the Rows values in arr_2_d array

arr_2_d.sum(axis=1)

array([ 15,  40,  65,  90, 115])

# Integer array indexing: 

When we index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array.

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.

print(a[[0, 1, 2], [0, 1, 0]])  

[1 4 5]


In [ ]:
# The above example of integer array indexing is equivalent to this:

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]


In [ ]:
# When using integer array indexing, you can reuse the same

print(a[[0, 0], [1, 1]]) 


[2 2]


In [ ]:
# Equivalent to the previous integer array indexing example

print(np.array([a[0, 1], a[0, 1]])) 

[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
import numpy as np

# Create a new array from which we will select elements

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)  

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Create an array of indices

b = np.array([0, 2, 0, 1])

In [ ]:
# Select one element from each row of a using the indices in b

print(a[np.arange(4), b])  

[ 1  6  7 11]


# Boolean array indexing: 

Boolean array indexing lets you pick out arbitrary elements of an array

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2) 

print(bool_idx)    

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# We use boolean array indexing to construct a rank 1 array consisting of the elements of a corresponding to the True values of bool_idx

print(a[bool_idx])  

[3 4 5 6]


In [ ]:
# We can do all of the above in a single concise statement:

print(a[a > 2])    

[3 4 5 6]


# Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that we can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

In [ ]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)       

int64


In [ ]:
x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)           

float64


In [ ]:
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                       

int64


# Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array

print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Elementwise difference; both produce the array

print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# Elementwise product; both produce the array

print(x * y)
print(np.multiply(x, y))


[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Elementwise division; both produce the array

print(x / y)
print(np.divide(x, y))


[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Elementwise square root; produces the array

print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


We now use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. 

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [ ]:
# Inner product of vectors; both produce 219

print(v.dot(w))
print(np.dot(v, w))

219
219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]

print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [ ]:
# Matrix / matrix product; both produce the rank 2 array


print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1))  # Compute sum of each row

10
[4 6]
[3 7]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply using the T attribute of an array object:

In [ ]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    
            
print(x.T)  

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
# Note that taking the transpose of a rank 1 array does nothing:

v = np.array([1,2,3])
print(v)    
print(v.T)  

[1 2 3]
[1 2 3]


Broadcasting


Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

In [ ]:
# Add the vector v to each row of the matrix x with an explicit loop

for i in range(4):
    y[i, :] = x[i, :] + v

In [ ]:
# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
y = x + vv  # Add x and vv elementwise
print(y) 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v.

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Here are some applications of broadcasting:

In [ ]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),

print(x + v)

[[2 2 4]
 [5 5 7]]


In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column.
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), 
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


# SciPy


Numpy provides a high-performance multidimensional array and basic tools to compute with and manipulate these arrays. SciPy builds on this, and provides a large number of functions that operate on numpy arrays and are useful for different types of scientific and engineering applications.

# Distance between points

SciPy defines some useful functions for computing distances between sets of points

In [ ]:
import numpy as np
from scipy.spatial.distance import pdist, squareform

# Create the following array where each row is a point in 2D space:
# [[0 1]
#  [1 0]
#  [2 0]]
x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

# Compute the Euclidean distance between all rows of x.
# d[i, j] is the Euclidean distance between x[i, :] and x[j, :],
# and d is the following array:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
d = squareform(pdist(x, 'euclidean'))
print(d)

[[0 1]
 [1 0]
 [2 0]]
[[0.         1.41421356 2.23606798]
 [1.41421356 0.         1.        ]
 [2.23606798 1.         0.        ]]


##Image operations


SciPy provides some basic functions to work with images. For example, it has functions to read images from disk into numpy arrays, to write numpy arrays to disk as images, and to resize images.